### ISSUE TITLE
missing stuff

### ISSUE THREAD

**Issue by MarcKunst** [lennartdeknikker/functional-programming#4]
Yoo Je hebt de volgende dingen nog niet toegevoegd aan je repo

- [x] schrijf je README
- [x] zet beschrijving in de wiki over je project
- [x] maak menu aan in wiki op juiste volgorde
- [x] concept, image toevoegen aan wiki
- [x] Deploy je project en voeg link toe

Misschien handig om bij je functional programming wiki je eigen understanding er van te benoemen

**Comment by lennartdeknikker** [comment]
Thanks, I made some updates in my documentation
